### ISSUE TITLE
[Bug]: Untitled bug report

### ISSUE THREAD

**Issue by GoogeTan** [Virtuoel/Statement#10]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.2

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

The game loading crash.

### Full list of installed mods

BetterEnd (Forge) 1.16.4.-1.6.0
Immersive Engineering 1.16.5-5.0.3-138
Statement Library 4.1.3+1.16.5-forge
Fluidlogged blocks 0.1.2

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/824900551.call(Unknown Source)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10:24:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ExceptionInInitializerError
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.state.StateHolder.statement_setEntries(SourceFile:653)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.state.StateHolder.statement_addEntry(SourceFile:613)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.state.StateContainer.statement_addProperty(SourceFile:555)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at virtuoel.statement.util.StateRefresherImpl.addProperty(StateRefresherImpl.java:49)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at virtuoel.statement.api.StateRefresher.addBlockProperty(StateRefresher.java:26)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Block.handler$zzb000$init(BlockMixin.java:572)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Block.<init>(BlockMixin.java:159)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.StairsBlock.<init>(StairsMixin.java:88)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:188)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$635/255301429.get(Unknown Source)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$643/1605718590.accept(Unknown Source)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$584/1855997464.run(Unknown Source)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:24:21] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[10:24:21] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.NullPointerException
[10:24:21] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at virtuoel.statement.util.HydrogenCompatibility.<clinit>(HydrogenCompatibility.java:13)
[10:24:21] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 26 more

**Comment by Micalobia** [comment]
This isn't even a bug report lmao
EDIT: After reading it a little more, it is a bug report, just a very weird one.

**Comment by Virtuoel** [comment]
Resolved in 4.2.0.
