### ISSUE TITLE
[Bug]: Mixin Failure 1.18

### ISSUE THREAD

**Issue by Micalobia** [Virtuoel/Statement#12]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.18

### Mod loader

Fabric

### Mod loader version

0.12.6

### Fabric API version

0.43.1+1.18

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

There was a mixin failure upon loading the game

### Full list of installed mods

Exclusively this mod in a fresh dev environment, with this as the only dependency and no code added except for what's seen in https://github.com/FabricMC/fabric-example-mod

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[16:22:22] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod statement failed statement.mixins.json:IdListMixin -> net.minecraft.util.collection.IdList: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_11100 was not located in the target class net.minecraft.util.collection.IdList. Using refmap Statement-refmap.json
 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_11100 was not located in the target class net.minecraft.util.collection.IdList. Using refmap Statement-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Block.<clinit>(Block.java:172) ~[minecraft-mapped.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) [minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) [minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) [minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) [minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[16:22:22] [main/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) ~[minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) ~[minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.6.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.util.collection.IdList failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Block.<clinit>(Block.java:172) ~[minecraft-mapped.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) ~[minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) ~[minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.6.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Block.<clinit>(Block.java:172) ~[minecraft-mapped.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) ~[minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) ~[minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.6.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [statement.mixins.json:IdListMixin] from phase [DEFAULT] in config [statement.mixins.json] from mod [statement] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Block.<clinit>(Block.java:172) ~[minecraft-mapped.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) ~[minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) ~[minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.6.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_11100 was not located in the target class net.minecraft.util.collection.IdList. Using refmap Statement-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Block.<clinit>(Block.java:172) ~[minecraft-mapped.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:286) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverDebugConfig.<clinit>(CarverDebugConfig.java:14) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.method_33968(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.carver.CarverConfig.<clinit>(CarverConfig.java:18) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.Carver.<clinit>(Carver.java:53) ~[minecraft-mapped.jar:?]
	at net.minecraft.world.gen.carver.ConfiguredCarvers.<clinit>(ConfiguredCarvers.java:29) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30572(BuiltinRegistries.java:51) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97) ~[minecraft-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96) ~[minecraft-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:410) ~[minecraft-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:52) ~[minecraft-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:147) ~[minecraft-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.6.jar:?]
	... 3 more

Process finished with exit code 1

**Comment by Micalobia** [comment]
The first mixin that fails is of `field_11100`, which is `idMap` in `IdListMixin`, they migrated the type from `IdentityHashMap` to `Object2IntMap`, might try to hunt down more if I have time

**Comment by Micalobia** [comment]
I've hunted as far as I can, continuing would be far outside the scope of what I know
- `IdListMixin` needs to migrate `idMap` from `IdentityHashMap` to `Object2IntMap`
- `StateManagerMixin` (`116plus`) needs to rename `method_30040` to `addFieldToMapCodec`
- `StateMixin` (`116plus`) needs to change `fieldOfProxy` inject point, or remove altogether, not sure

At this point, the error I hit was that something, somewhere, was having a problem with `aii$b.a` not being remapped to `net/minecraft/util/dynamic/Codecs$Lazy.delegate` correctly, which I'm 95% sure is because it was turned into a record, which mixins have trouble with

**Comment by Virtuoel** [comment]
Resolved in 4.2.0.
