### ISSUE TITLE
[Bug]: 1.19.2 mixin refmap error

### ISSUE THREAD

**Issue by dhyces** [Virtuoel/Statement#19]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.52

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Running a dedicated server in my dev environment immediately causes a crash due to a mixin apply error. This is specific to 1.19.2, which I understand isn't technically supported by you yet, though I wanted to make sure you were aware of this.

### Full list of installed mods

Dev env, just forge, statement, and my own mod

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[21Nov2022 22:35:25.710] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserveruserdev, --gameDir, ., --fml.forgeVersion, 43.1.52, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --mixin.config, wartdecay.mixins.json]
[21Nov2022 22:35:25.717] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.2 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[21Nov2022 22:35:25.934] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/user/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%23125!/ Service=ModLauncher Env=SERVER
[21Nov2022 22:35:26.357] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\javafmllanguage\1.19.2-43.1.52\15567d99c9572096b38b5ce4d5d3d205b2356e47\javafmllanguage-1.19.2-43.1.52.jar is missing mods.toml file
[21Nov2022 22:35:26.363] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\lowcodelanguage\1.19.2-43.1.52\25cf253a5814c855c978bb7dc808d5991adb5eaf\lowcodelanguage-1.19.2-43.1.52.jar is missing mods.toml file
[21Nov2022 22:35:26.369] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\mclanguage\1.19.2-43.1.52\b6cfdb1c54bb57ffee28f7591f1f19c57f29dfb4\mclanguage-1.19.2-43.1.52.jar is missing mods.toml file
[21Nov2022 22:35:26.374] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\fmlcore\1.19.2-43.1.52\1522df0ea44e9447d69d877190a2540576361f12\fmlcore-1.19.2-43.1.52.jar is missing mods.toml file
[21Nov2022 22:35:26.490] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[21Nov2022 22:35:28.007] [main/WARN] [mixin/]: Compatibility level JAVA_17 specified by wartdecay.mixins.json is higher than the maximum level supported by this version of mixin (JAVA_13).
[21Nov2022 22:35:28.008] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[21Nov2022 22:35:28.017] [main/INFO] [mixin/]: Compatibility level JAVA_8 specified by statement.mixins.json is lower than the default level supported by the current mixin service (JAVA_16).
[21Nov2022 22:35:28.019] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserveruserdev' with arguments [--gameDir, .]
[21Nov2022 22:35:28.132] [main/INFO] [mixin/]: Attempting to load Fernflower decompiler (Threaded mode)
[21Nov2022 22:35:28.135] [main/INFO] [mixin/]: Fernflower could not be loaded, exported classes will not be decompiled. NoClassDefFoundError: org/jetbrains/java/decompiler/main/extern/IResultSaver
[21Nov2022 22:35:28.146] [main/INFO] [mixin/]: Preparing mixins for MixinEnvironment[DEFAULT]
[21Nov2022 22:35:28.147] [main/INFO] [mixin/]: Selecting config wartdecay.mixins.json
[21Nov2022 22:35:28.155] [main/INFO] [mixin/]: Selecting config statement.mixins.json
[21Nov2022 22:35:28.527] [main/INFO] [mixin/]: Remapping refMap Statement-refmap.json using C:\Users\user\OneDrive\Desktop\DevStuff\Java\wart-decay\Forge/build/createSrgToMcp/output.srg
[21Nov2022 22:35:28.527] [main/INFO] [mixin/]: Preparing wartdecay.mixins.json (2)
[21Nov2022 22:35:28.591] [main/INFO] [mixin/]: Preparing statement.mixins.json (44)
[21Nov2022 22:35:28.839] [main/INFO] [mixin/]: Prepared 26 mixins in 0.691 sec (26.6ms avg) (0ms load, 0ms transform, 0ms plugin)
[21Nov2022 22:35:28.890] [main/INFO] [mixin/]: Mixing server.MinecraftDedicatedServerMixin from statement.mixins.json into net.minecraft.server.dedicated.DedicatedServer
[21Nov2022 22:35:28.988] [main/FATAL] [MixinProcessor/]: /****************************************************************************************************************************************************************************************/
[21Nov2022 22:35:28.989] [main/FATAL] [MixinProcessor/]: /*                                                                                    Invalid Mixin                                                                                     */
[21Nov2022 22:35:28.989] [main/FATAL] [MixinProcessor/]: /*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21Nov2022 22:35:28.989] [main/FATAL] [MixinProcessor/]: /*     Action : APPLY                                                                                                                                                                   */
[21Nov2022 22:35:28.990] [main/FATAL] [MixinProcessor/]: /*      Mixin : virtuoel.statement.mixin.server.MinecraftDedicatedServerMixin                                                                                                           */
[21Nov2022 22:35:28.990] [main/FATAL] [MixinProcessor/]: /*     Config : statement.mixins.json                                                                                                                                                   */
[21Nov2022 22:35:28.990] [main/FATAL] [MixinProcessor/]: /*      Phase : DEFAULT                                                                                                                                                                 */
[21Nov2022 22:35:28.991] [main/FATAL] [MixinProcessor/]: /*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21Nov2022 22:35:28.992] [main/FATAL] [MixinProcessor/]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException                                                                                                       */
[21Nov2022 22:35:28.992] [main/FATAL] [MixinProcessor/]: /*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21Nov2022 22:35:28.993] [main/FATAL] [MixinProcessor/]: /*     @Inject annotation on onSetupServer specifies a target class 'net/minecraft/server/ServerInterface', which is not supported [PREINJECT Applicator Phase ->                       */
[21Nov2022 22:35:28.993] [main/FATAL] [MixinProcessor/]: /*     statement.mixins.json:server.MinecraftDedicatedServerMixin -> Prepare Injections ->  ->                                                                                          */
[21Nov2022 22:35:28.994] [main/FATAL] [MixinProcessor/]: /*     handler$zbd000$onSetupServer(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]                                                                 */
[21Nov2022 22:35:28.994] [main/FATAL] [MixinProcessor/]: /*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[21Nov2022 22:35:28.995] [main/FATAL] [MixinProcessor/]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on onSetupServer specifies a target class                                         */
[21Nov2022 22:35:28.995] [main/FATAL] [MixinProcessor/]: /*     'net/minecraft/server/ServerInterface', which is not supported [PREINJECT Applicator Phase -> statement.mixins.json:server.MinecraftDedicatedServerMixin ->                      */
[21Nov2022 22:35:28.995] [main/FATAL] [MixinProcessor/]: /*     Prepare Injections ->  -> handler$zbd000$onSetupServer(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]                                       */
[21Nov2022 22:35:28.996] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parseSelectors(InjectionInfo.java:355)                                       */
[21Nov2022 22:35:28.997] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:329)                                       */
[21Nov2022 22:35:28.998] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)                                               */
[21Nov2022 22:35:28.998] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)                                               */
[21Nov2022 22:35:28.998] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)                                */
[21Nov2022 22:35:28.998] [main/FATAL] [MixinProcessor/]: /*         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                     */
[21Nov2022 22:35:28.999] [main/FATAL] [MixinProcessor/]: /*         java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)                                                              */
[21Nov2022 22:35:28.999] [main/FATAL] [MixinProcessor/]: /*         java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                      */
[21Nov2022 22:35:28.999] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)                                                                                          */
[21Nov2022 22:35:28.999] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)                                                                                                    */
[21Nov2022 22:35:28.999] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)                                 */
[21Nov2022 22:35:29.000] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)                                                */
[21Nov2022 22:35:29.000] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311)                              */
[21Nov2022 22:35:29.000] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)                    */
[21Nov2022 22:35:29.001] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)                            */
[21Nov2022 22:35:29.001] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)                                 */
[21Nov2022 22:35:29.001] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)                                           */
[21Nov2022 22:35:29.002] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)                                     */
[21Nov2022 22:35:29.002] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)                                             */
[21Nov2022 22:35:29.003] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)                                      */
[21Nov2022 22:35:29.003] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)                  */
[21Nov2022 22:35:29.003] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)                                     */
[21Nov2022 22:35:29.003] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)                           */
[21Nov2022 22:35:29.004] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)                                       */
[21Nov2022 22:35:29.004] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)                                                          */
[21Nov2022 22:35:29.005] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)                              */
[21Nov2022 22:35:29.005] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)                                                                            */
[21Nov2022 22:35:29.005] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)                                                                      */
[21Nov2022 22:35:29.005] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)                                                                           */
[21Nov2022 22:35:29.006] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)                                                                                */
[21Nov2022 22:35:29.006] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)                                                                                */
[21Nov2022 22:35:29.006] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)                                                                                                              */
[21Nov2022 22:35:29.006] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Class.getDeclaredMethods0(Native Method)                                                                                                                 */
[21Nov2022 22:35:29.006] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)                                                                                                         */
[21Nov2022 22:35:29.007] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)                                                                                                               */
[21Nov2022 22:35:29.007] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Class.getMethod0(Class.java:3529)                                                                                                                        */
[21Nov2022 22:35:29.007] [main/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Class.getMethod(Class.java:2225)                                                                                                                         */
[21Nov2022 22:35:29.007] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/fmlloader@1.19.2-43.1.52/net.minecraftforge.fml.loading.targets.ForgeServerUserdevLaunchHandler.lambda$launchService$0(ForgeServerUserdevLaunchHandler.java:22) */
[21Nov2022 22:35:29.008] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)                                    */
[21Nov2022 22:35:29.008] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)                                                      */
[21Nov2022 22:35:29.008] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)                                                      */
[21Nov2022 22:35:29.009] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)                                                                                */
[21Nov2022 22:35:29.009] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)                                                                                */
[21Nov2022 22:35:29.009] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)                                                */
[21Nov2022 22:35:29.009] [main/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)                                                */
[21Nov2022 22:35:29.010] [main/FATAL] [MixinProcessor/]: /*         cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)                                                               */
[21Nov2022 22:35:29.010] [main/FATAL] [MixinProcessor/]: /****************************************************************************************************************************************************************************************/
[21Nov2022 22:35:29.010] [main/FATAL] [mixin/]: Mixin apply failed statement.mixins.json:server.MinecraftDedicatedServerMixin -> net.minecraft.server.dedicated.DedicatedServer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on onSetupServer specifies a target class 'net/minecraft/server/ServerInterface', which is not supported [PREINJECT Applicator Phase -> statement.mixins.json:server.MinecraftDedicatedServerMixin -> Prepare Injections ->  -> handler$zbd000$onSetupServer(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on onSetupServer specifies a target class 'net/minecraft/server/ServerInterface', which is not supported [PREINJECT Applicator Phase -> statement.mixins.json:server.MinecraftDedicatedServerMixin -> Prepare Injections ->  -> handler$zbd000$onSetupServer(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parseSelectors(InjectionInfo.java:355) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:329) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getMethodsRecursive(Class.java:3543) ~[?:?]
	at java.lang.Class.getMethod0(Class.java:3529) ~[?:?]
	at java.lang.Class.getMethod(Class.java:2225) ~[?:?]
	at net.minecraftforge.fml.loading.targets.ForgeServerUserdevLaunchHandler.lambda$launchService$0(ForgeServerUserdevLaunchHandler.java:22) ~[fmlloader-1.19.2-43.1.52.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23113!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

</p>

**Comment by Virtuoel** [comment]
This should now be resolved as of the 4.2.5 release.
