### ISSUE TITLE
Using Statement breaks server world generation

### ISSUE THREAD

**Issue by Eilux** [Virtuoel/Statement#4]
I'm not really sure why this happens but the end result looks like this: 
![2020-11-18_14 16 21](https://user-images.githubusercontent.com/46938341/99580302-51007e80-29ad-11eb-9429-0f24cc88f4e5.png)
The entire world is made of large cubes of blackstone pressure plates and walls

here is a world with the same effect: 
[Broken_World.zip](https://github.com/Virtuoel/Statement/files/5562488/Broken_World.zip)

also on the client side this error message keeps apearing: 
```
java.lang.NullPointerException: null
	at net.minecraft.world.World.setBlockState(World.java:182) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.world.World.setBlockState(World.java:172) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.world.ClientWorld.setBlockStateWithoutNeighborUpdates(ClientWorld.java:340) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onBlockUpdate(ClientPlayNetworkHandler.java:771) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.BlockUpdateS2CPacket.apply(BlockUpdateS2CPacket.java:41) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.BlockUpdateS2CPacket.apply(BlockUpdateS2CPacket.java:19) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:20) ~[minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:136) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:22) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:109) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:97) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:979) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.4-mapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

Here is the log:
[latest.log](https://github.com/Virtuoel/Statement/files/5562546/latest.log)

**Comment by Virtuoel** [comment]
This is likely just a visual issue. What MC version are you on, and which mods are present on both the client and the server?

**Comment by Eilux** [comment]
1.16.4 its just Betterslabs

**Comment by Eilux** [comment]
https://github.com/Eilux/BetterSlabs
